version: 2
jobs:
  build:
    docker:
      # On utilise l'image custom qui utilise node et mysql.
      # https://hub.docker.com/r/mohelkar/test/tags/
      - image: mohelkar/test
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_USER=root
          - MYSQL_DATABASE=covogreen

    working_directory: ~/covogreen

    steps:
      - checkout

      # On restaure le cache du backend.
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/covogreen/covogreen-back/package.json" }}
            - v1-dependencies-

      # On installe les dépendances du backend.
      - run:
          name: Update covogreen-back
          command: cd ~/covogreen/covogreen-back && npm install

      # On restaure le cache du frontend.
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "~/covogreen/covogreen-front/package.json" }}
            - v2-dependencies-

      # On installe les dépendances du frontend.
      - run:
          name: Update des dépendances du front
          command: cd ~/covogreen/covogreen-front && npm install

      - run:
          name: Lancement service mysql
          command: /etc/init.d/mysql start

      - run:
          name: Creation de la database
          command: mysql -u root -e "create database covogreen"

      - run:
          name: Ajout des requetes
          command: mysql -u root covogreen < ~/covogreen/database.sql
      - run:
          name: Ajout des procedures
          command: mysql -u root covogreen < ~/covogreen/procedures_stock.sql

      # On restore le cache si on a déjà dll les dependances du backend.
      - save_cache:
          paths:
            - ~/covogreen/covogreen-back/node_modules
          key: v1-dependencies-{{ checksum "~/covogreen/covogreen-back/package.json" }}

      # On restore le cache si on a déjà dll les dependances du frontend.
      - save_cache:
          paths:
            - ~/covogreen/covogreen-front/node_modules
          key: v2-dependencies-{{ checksum "~/covogreen/covogreen-front/package.json" }}

      # On lance le test du covogreen-back.
      - run:
          name: Test covogreen-back
          command: cd ~/covogreen/covogreen-back && npm test

      # On lance le test du covogreen-front.
      - run:
          name: Test covogreen-front
          command: cd ~/covogreen/covogreen-front && npm test